name: Test Builds
on:
  push:
    branches:
      - master

env:
  MESON_VERSION: '0.63.3'
  EM_VERSION: '3.1.51'
  EM_CACHE_FOLDER: 'emsdk'
  TAISEI_NOPRELOAD: 0
  TAISEI_PRELOAD_REQUIRED: 1

jobs:
  linux-test-build:
    name: Linux (x86)
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install Tools
      run: >
        sudo apt update || true # debian cache is not atomic and can sometimes fail

        sudo apt install -y -qq
        build-essential
        libsdl2-dev
        libogg-dev
        libopusfile-dev
        libpng-dev
        libzip-dev
        libx11-dev
        libwayland-dev
        python3-docutils
        libwebp-dev
        libfreetype6-dev
        libzstd-dev
        libssl-dev

        pip install
        meson==${{ env.MESON_VERSION }}
        ninja
        zstandard

    - name: Configure
      run: >
        meson setup build/
        --native-file misc/ci/common-options.ini
        --native-file misc/ci/nofallback.ini
        --native-file misc/ci/linux-x86_64-build-test-ci.ini
        --prefix=$(pwd)/build-test

    - name: Build
      run: |
        meson compile -C build/ --verbose
        meson install -C build/

    - name: Run Test
      run: $(pwd)/build-test/bin/taisei -R $(pwd)/misc/ci/tests/test-replay.tsr

    - name: Upload Log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: taisei
        path: cat /home/runner/work/taisei/taisei/build/meson-logs/meson-log.txt
        if-no-files-found: warn

   